spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
#        default_batch_fetch_size: 1000
        format_sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: debug